# FUNDING.yml
# Configuration for funding options in the SecureWave PAM.API repository

github: vinodvin42          # GitHub Sponsors (replace with your GitHub username)
patreon: vinodvin42         # Patreon (replace with your Patreon username)
ko_fi: vinodvin42           # Ko-fi (replace with your Ko-fi username)
open_collective: vinodvin42 # Open Collective (replace with your Open Collective name)
